"theme-bootstrap-2" :
  "use" : "theme"


"posts" :
  "sort" : ["date", "desc"]
  "summary_lines" : 10
  "latest" : 5

"todo" :
  "sort" : ["date", "desc"]
  "summary_lines" : 10
  "latest" : 5

"kramdown":
  "use": "ignore"
"pdf":
  "use": "ignore"
